org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=anticreativedrift
mod_name=Anti Creative Drift
mod_license=Apache 2.0
mod_version=1.1+1.20.1-forge
mod_group_id=dev.nonamecrackers2.anticreativedrift
mod_authors=nonamecrackers2
mod_description=Disables the 'drift' when flying in creative

crackerslib_version=1.20.1-0.4.4
crackerslib_version_range=[1.20.1-0.4.4,)